spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFmyDRuiTMzUX1HSNzJ
      secret-key: XjV4rl55S8uqqMaPDE52rn8NPZhgKe
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimail-luoxu
#    alibaba:
#      cloud:
#        access-key: LTAI5tFmyDRuiTMzUX1HSNzJ
#        secret-key: XjV4rl55S8uqqMaPDE52rn8NPZhgKe
#        oss:
#          endpoint: oss-cn-chengdu.aliyuncs.com
#          bucket: gulimail-luoxu
#    alicloud:
#      sms:
#        host: https://fesms.market.alicloudapi.com
#        path: /sms/
#        skin: 1
#        sign: 175622
#        appcode: b0563c23aff8428c97a54d4f7f9e28e5


  application:
    name: gulimail-third-party

server:
  port: 30000


#alibaba:
#  cloud:
#    access-key: LTAI5tFmyDRuiTMzUX1HSNzJ
#    secret-key: XjV4rl55S8uqqMaPDE52rn8NPZhgKe
#    oss:
#      endpoint: oss-cn-chengdu.aliyuncs.com
#      bucket: gulimail-luoxu